import os
import sys
from scripts.parser import fluid_parser
from scripts.core import version, translate
from scripts import fluid_infobox

header = f"""
{{{{Header|Project Zomboid|Fluids}}}}
{{{{Page version|{version.get_version()}}}}}
{{{{Autogenerated|fluids|source=https://github.com/Vaileasys/pz-wiki_parser}}}}
"""

# Gets similar fluids based on a calculated score
def calculate_similar_fluids(fluid_id, fluid_data):
    weights = {
        "categories": 3,
        "poison": 3,
        "fatigueChange": 1,
        "hungerChange": 1,
        "stressChange": 1,
        "thirstChange": 1,
        "unhappyChange": 1,
        "calories": 0.5,
        "carbohydrates": 0.5,
        "lipids": 0.5,
        "proteins": 0.5,
        "alcohol": 3,
        "fluReduction": 2,
        "painReduction": 2,
        "enduranceChange": 1,
        "foodSicknessReduction": 2
    }

    poison_effect = {
        'None': 0,
        'Mild': 1,
        'Medium': 2,
        'Severe': 3,
        'Extreme': 4,
        'Deadly': 5
    }

    compared_fluids = fluid_parser.get_fluid_data()
    target_fluid = process_fluid_data(fluid_id, fluid_data)
    similar_fluids = []

    # Get values and scores for all other fluids
    for other_id, other_data in compared_fluids.items():
        if other_id == fluid_id:
            continue

        compared_fluid = process_fluid_data(other_id, other_data)
        score = 0

        # Compare categories
        shared_categories = set(target_fluid['categories']) & set(compared_fluid['categories'])
        score += len(shared_categories) * weights['categories']

        # Compare poison
        target_poison = poison_effect.get(target_fluid['poison'], 0)
        other_poison = poison_effect.get(compared_fluid['poison'], 0)
        score += weights['poison'] * min(target_poison, other_poison)

        # Compare properties
        for prop, weight in weights.items():
            if prop in target_fluid['properties'] and prop in compared_fluid['properties']:
                target_value = target_fluid['properties'][prop]
                compared_value = compared_fluid['properties'][prop]
                if target_value == compared_value:
                    score += weight

        # Append the other fluid's DisplayName and score
        similar_fluids.append({'name': other_data.get('DisplayName', 'Fluid'), 'score': score})

    # Sort and return the top 3 names
    similar_fluids.sort(key=lambda x: x['score'], reverse=True)
    processed_links = []
    for fluid in similar_fluids[:3]:
        display_name = fluid['name']
        display_name_prefix = "Fluid_Name_"
        if display_name.startswith(display_name_prefix):
            display_name = display_name[len(display_name_prefix):]
        name_en = translate.get_translation(display_name, 'FluidID', 'en')
        name_translated = name_en

        page_name = f"{name_en} (fluid)"
        language_code = translate.get_language_code()
        if language_code != 'en':
            name_translated = translate.get_translation(display_name, 'FluidID')
            page_name = f"{page_name}/{language_code}"
        wiki_link = f"[[{page_name}|{name_translated}]]"
        processed_links.append(wiki_link)

    return processed_links


def process_fluid_data(fluid_id, fluid_data):
    # Process name
    display_name = fluid_data.get('DisplayName', 'Fluid')
    display_name_prefix = "Fluid_Name_"
    if display_name.startswith(display_name_prefix):
        display_name = display_name[len(display_name_prefix):]
    name = translate.get_translation(display_name, 'FluidID')

    categories = fluid_data.get('Categories', [])


    blend_whitelist = fluid_data.get('BlendWhiteList', {})
    whitelist = blend_whitelist.get('whitelist', False)
    whitelist_categories = blend_whitelist.get('categories', [])

    properties_data = {}
    if 'Properties' in fluid_data:
        properties_data = fluid_data['Properties']

    poison_data = {}
    if 'Poison' in fluid_data:
        poison_data = fluid_data['Poison']
    poison_max_effect = poison_data.get('maxEffect', 'None')

    processed_fluid_data = {
        'name': name,
        'whitelist': whitelist,
        'whitelist_categories': whitelist_categories,
        'properties': properties_data,
        'poison': poison_max_effect,
        'categories': categories
    }

    return processed_fluid_data


def generate_article(infobox_dir, output_dir):
    fluid_parser.get_fluid_data()
    for fluid_id, fluid_data in fluid_parser.get_fluid_data().items():

        output_file_path = os.path.join(output_dir, f"{fluid_id}.txt")
        infobox_file_path = os.path.join(infobox_dir, f"{fluid_id}.txt")

        # Read infobox data
        try:
            if os.path.exists(infobox_file_path):
                with open(infobox_file_path, 'r', encoding='utf-8') as file:
                    infobox_content = file.read()
            else:
                print(f"File not found for '{fluid_id}'. Try generating infoboxes again.")
                infobox_content = f"{{{{Infobox fluid\n|name=\n|categories=\n|fluid_color=0, 0, 0\n|fluid_id=Base.{fluid_id}\n|infobox_version={version.get_version()}\n}}}}"
        except Exception as e:
            print(f"Error reading infobox file '{infobox_file_path}': {e}")

        processed_fluid_data = process_fluid_data(fluid_id, fluid_data)

        try:
            with open(output_file_path, 'w', encoding='utf-8') as file:
                # Header
                file.write(header)

                # Infobox
                file.write(infobox_content)

                # Intro
                file.write(f"\n'''{processed_fluid_data['name'].capitalize()}''' is a [[fluid]] that can be found in [[fluid container]]s.")

                # Usage
                file.write(f"\n\n==Usage==")
                file.write(f"\nLike other [[fluid]]s, {processed_fluid_data['name'].lower()} can be stored in a [[fluid container]], which may be an [[item]] or [[tile|entity]].")
                if processed_fluid_data['whitelist']:
                    file.write(f"\n===Mixing===")
                    if not processed_fluid_data['whitelist_categories']:
                        file.write("\nThis item cannot be mixed with other fluids.")
                    else:
                        file.write("\nThis item can be mixed with fluids that have the following categories:")
                        file.write(f"\n*{'\n*'.join(processed_fluid_data['whitelist_categories'])}")

                file.write(f"\n\n==See also==")
                file.write(f"\n*{'\n*'.join(calculate_similar_fluids(fluid_id, fluid_data))}")

        except Exception as e:
            print(f"Error writing article file '{output_file_path}': {e}")        


def main():
    language_code = translate.get_language_code()
    # Check if fluid infoboxes have been generated
    infobox_dir = f"output/{language_code}/fluid_infoboxes/"
    output_dir = f"output/{language_code}/fluid_articles"
    if not os.path.exists(infobox_dir):
        while True:
            print(f"The infobox '{infobox_dir}' does not exist.")
            user_input = input("Want to generate fluid infoboxes? (Y/N)\n> ").strip().lower()

            if user_input == "y":
                print("Running 'fluid_infobox.py'...")
                fluid_infobox.main()
                break
            elif user_input == "n":
                print("Exiting script...")
                sys.exit(1)
            else:
                print("Invalid input.")
                continue
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    print("Generating articles...")

    generate_article(infobox_dir, output_dir)

if __name__ == "__main__":
    main()